### ISSUE TITLE
Development discussion

### ISSUE THREAD

**Issue by Alovchin91** [Alovchin91/flac-winrt#6] opened 2014-11-04 13:08 UTC
Better late than never :smile:
Welcome to the development discussion of **FLAC for Windows Runtime** project.
Here we discuss the development process of the project and all related stuff. If you think you could help, feel free to collaborate!

**Comment by mcosmin222** [comment] 2015-01-04 16:03
Happy new year xD

**Comment by Alovchin91** [comment] 2015-01-04 20:17
@mcosmin222 Hey! Happy New Year! :)

**Comment by Alovchin91** [comment] 2015-01-25 17:04
**Update**
Recent update to FLAC for Windows Runtime introduced an experimental deferrals mechanism. You can use deferrals to make your callbacks asynchronous.
For now, deferrals are available only for Read and Write Callbacks. You can obtain `IDeferral` by calling `StreamDecoderWriteEventArgs.GetDeferral`. Don't forget to call `IDeferral.Complete` after you have finished your async operation!

**Comment by mcosmin222** [comment] 2015-01-25 17:09
Omg you are back <3

**Comment by Alovchin91** [comment] 2015-01-25 17:20
@mcosmin222 Ha, I have always been around! :smile: I was thinking about some improvements, so I ended up making a deferrals mechanism.

**Comment by Alovchin91** [comment] 2015-01-25 17:43
You can now take [release v1.1.0](../releases/tag/v1.1.0) that includes new callbacks introduced in November and experimental deferrals support!

**Comment by mcosmin222** [comment] 2015-01-25 18:51
I am having a weird issue. Sometimes, when checking between flac tracks, I get a fail fast exception, because of failed assertions at various points of the decoder related to frame decoding.. They seem to be completely random...

**Comment by mcosmin222** [comment] 2015-01-25 19:07
Foe example

			::FLAC__StreamDecoderWriteStatus StreamDecoder::write_callback_(const ::FLAC__StreamDecoder *decoder, const ::FLAC__Frame *frame, const FLAC__int32 * const buffer[], void *client_data)
			{
				(void)decoder;
				FLAC__ASSERT(0 != client_data);
				StreamDecoder^ instance = reinterpret_cast<StreamDecoder^>(client_data);
				FLAC__ASSERT(nullptr != instance && instance->IsValid);
				Callbacks::StreamDecoderWriteEventArgs^ args = ref new Callbacks::StreamDecoderWriteEventArgs(buffer, frame);
				instance->WriteCallback(instance, args);
				return args->Result;
			}

the second FLAC__ASSERT fails, for some unusual reason. Pretty much the IsValid property fails.

**Comment by Alovchin91** [comment] 2015-01-25 19:26
@mcosmin222 Well, `IsValid` is implemented this way:
```cpp
bool StreamDecoder::IsValid::get()
{
    return 0 != decoder_ && ReferenceEquals(file_stream_, nullptr) == ReferenceEquals(file_reader_, nullptr);
}
```
So, IsValid can fail if `decoder_` is null, which should never be the case, or when `file_stream_` is null and `file_reader_` is not, or otherwise. This might happen if there is a race condition in your code.

**Comment by mcosmin222** [comment] 2015-01-25 19:31
Race condition you say? Yes, I suspected something like that might be the issue, but the only race condition I found is when the user skips through tracks way too fast and there is an on-going sample request from the former track and the current track at the same time.


 I do set the entire decoder object to nullptr on media stream source closed event, but the pipeline shouldn't be asking for samples at that point, aside from when there's actually 2 active media stream sources at the same time...


I still think the usage of Assert is a bit extreme for these cases. It throws a second chance exception which you can't catch. I think the API should throw an exception instead of having the asserts...it's your call :)

**Comment by Alovchin91** [comment] 2015-01-25 19:33
@mcosmin222 Try recompiling the latest source and checking. If this doesn't solve the problem, then there is a race condition.

**Comment by mcosmin222** [comment] 2015-01-25 19:33
Did you do anything else than the deferals?

**Comment by Alovchin91** [comment] 2015-01-25 19:35
@mcosmin222 Assert should work only in Debug builds. In Release, there will be an exception - for example, NullReferenceException :wink: I'm not sure when the Closed event is called on a MediaStreamSource - I have never been able to catch this moment. But the `file_stream_` and `file_reader_` are only assigned in `Open` and `Finish` methods, so look at those.

**Comment by Alovchin91** [comment] 2015-01-25 19:37
@mcosmin222 I have just added a `nullptr` initializer for `file_reader_`. While WinRT types should be automatically initialized to null, standard C++ classes can be initialized to garbage. This is just an over-care, but who knows.

**Comment by Alovchin91** [comment] 2015-01-25 19:38
@mcosmin222 Please try the latest source and tell me the result. If this solves your problem, I'll update release v1.1.0.

**Comment by mcosmin222** [comment] 2015-01-25 19:41
The closing event is fired when the next track starts playing. 
So the sequence is something like this:

last sample > get next track > last media stream source closing / new media stream source starting. The latter 2 happen almost simultaneous. 

Ok I will try it. Hope there won't be too many API changes to break my code xD

**Comment by Alovchin91** [comment] 2015-01-25 19:47
@mcosmin222 If you used version with new callbacks, there will be no API
changes for you :)

I have also found a good way to reduce memory consumption. After calling
`StreamDecoderWriteEventArgs.GetBuffer()` you should call
`GC.AddMemoryPressure(buffer.Capacity)` to let GC know about unmanaged
memory used by IBuffer.

**Comment by mcosmin222** [comment] 2015-01-25 19:52
I am doing 100% unmanaged decoders. There is a trade of between performance (C# ones are faster) and memory managements (C++ releases memory faster). The issue still remains even with the new API, but I did not try it in release mode. Just debug. I will try again in release.

**Comment by Alovchin91** [comment] 2015-01-25 19:54
@mcosmin222 Oh, so you write decoders in C++? And the background task too?

**Comment by mcosmin222** [comment] 2015-01-25 19:55
The background task is C# as it needs some classes from managed libraries. Decoders are C++.

**Comment by Alovchin91** [comment] 2015-01-25 19:56
@mcosmin222 That's interesting. Is this why your decoders take so little memory? :)

**Comment by mcosmin222** [comment] 2015-01-25 19:57
Maybe. I am not sure. The C# ones didn't take much either but the GC eventually stops collecting in time and lets the memory build up. in C# i used the GC.AddMemoryPreasure thingy you said earlier.

**Comment by mcosmin222** [comment] 2015-01-25 19:59
As James said on forums, the deterministic GC does make a difference but not from what he said. The GC never stops the media pipeline, it runs concurrently. But the memory in C++ self releases, so there is no need for a GC, and it stays at lower levels.

**Comment by Alovchin91** [comment] 2015-01-25 20:04
@mcosmin222 This makes sense. Seems like it would be better to rewrite examples in C++, too. Maybe even implement MFTs.

**Comment by mcosmin222** [comment] 2015-01-25 20:04
Testing in release mode appears to have fixed the problem but I am not celebrating yet xD
The asserts should still be replaced by exception throws. It makes actual code debugging much harder. The problem is, on windows phone, the fail of assertion simply kills the process and does not display an error message like it does on desktop windows.

**Comment by mcosmin222** [comment] 2015-01-25 20:08
I think MFTs are a bit too much. Media stream sources should be enough. As james said, MFT's are not meant to be used for background audio.

**Comment by mcosmin222** [comment] 2015-01-25 20:27
I think there still is a race somewhere in my code. When I find it, I will fix it and post the media stream source code here.

**Comment by Alovchin91** [comment] 2015-01-25 20:31
@mcosmin222 Okay :) Regarding asserts - I'll consider replacing them with exceptions, but then you will get an exception even in release ;)

**Comment by mcosmin222** [comment] 2015-01-25 20:34
Well didn;t you say asserts morph into exceptions in release mode?

**Comment by Alovchin91** [comment] 2015-01-25 20:48
@mcosmin222 No. I meant that in release mode they will be skipped, and there may appear exceptions in the code that is "guarded" by those asserts.

**Comment by mcosmin222** [comment] 2015-01-25 20:51
Ok then. Leave em that way..xD

**Comment by mcosmin222** [comment] 2015-02-22 17:56
So any idea on how one would implement gapless playback?

**Comment by Alovchin91** [comment] 2015-03-01 07:57
@mcosmin222 Hmm, I suppose you should implement some kind of pre-loading the next MSS by the end of the previous. Good part is that you need this only by the end of the song, because in all other cases (for example, manually switching songs) you don't need gapless playback.

**Comment by mcosmin222** [comment] 2015-03-01 07:59
Already did that..:)

I was wondering if it ok to mention you in some technet article about media stream sources in winRT:p

Sent from my Windows Phone
________________________________

**Comment by Alovchin91** [comment] 2015-03-01 08:00
@mcosmin222 Yeah, of course, I would appreciate that :)

**Comment by mcosmin222** [comment] 2015-04-15 15:03
Happy Easter :P

Soooo...whats up?

**Comment by Alovchin91** [comment] 2015-04-15 20:10
@mcosmin222 Hey, happy Easter :) I'm currently slooooowly working on Windows 10 UAP versions of Vorbis and Opus codecs; I want to wait until //build/ before publishing them though. And I'm not sure if there's any need in updating FLAC codec for UAP since Windows 10 supports FLAC out of the box...

**Comment by mcosmin222** [comment] 2015-04-15 20:29
The thing is, universal music app won't really work since they will likely keep the shared background media player resource on phone and use media elements on desktop/tablet. Or at least i hope so, I don't need another breaking change for my player >.>

We could create new codecs though...

Sent from my Windows Phone
________________________________

**Comment by Alovchin91** [comment] 2015-05-10 18:37
Just committed a new portion of changes.
First of all, **IDeferral** is now being awaited synchronously. I replace `AsyncCountdownEvent` with synchronous `CountdownEvent`, so no more overhead for synchronously performing the waiting task.
Second, I took advantage of deferrals and changed implementation of callbacks that are being used when `StreamDecoder` is initialized with `IRandomAccessStream` (main scenario). They now use corresponding `EventArgs`, and the Read callback uses deferral to asynchronously work with `DataReader`.
Finally, I changed implementation of helper's `pack_sample` methods so that they are now using `DataWriter` instead of tricks with getting `IBuffer`'s underlying array.
Please feel free to check it out!

**Comment by Alovchin91** [comment] 2015-05-10 18:38
The next update I expect will be completely about moving to **libFLAC 1.3.1**.

**Closed** 2020-02-01 22:42 UTC
